parameters:
    entity: 'ParserBundle:Item'
services:
    mapping.converter:
        class: Ddeboer\DataImport\Step\MappingStep
    constraint.helper:
        class: ParserBundle\Helper\ConstraintHelper
        arguments: ['@validator']
    doctrine.writer:
        class: Ddeboer\DataImport\Writer\DoctrineWriter
        arguments: ['@doctrine.orm.default_entity_manager', '%entity%']
    factory.parser_factory:
        class: ParserBundle\Factory\ParserFactory
        arguments: ['@doctrine.writer', '@validator', '@mapping.converter', '@logger', '@doctrine.orm.default_entity_manager', '@constraint.helper']
    service.parser_service:
        class: ParserBundle\Service\ParserService
        arguments: ['@factory.parser_factory', '@doctrine.orm.default_entity_manager']
